// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjSc-NG7P_xX2ff6vHbpiX8DcB9Twelp4',
    appId: '1:901564160466:web:71ed520bb891528ecfd00b',
    messagingSenderId: '901564160466',
    projectId: 'olympe-4f6cc',
    authDomain: 'olympe-4f6cc.firebaseapp.com',
    storageBucket: 'olympe-4f6cc.appspot.com',
    measurementId: 'G-76BVVHZVLZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQ2eIeXWxK5zd5IjzsbFnrySy_eDyfnAs',
    appId: '1:901564160466:android:bf1d1df4d15d2e4acfd00b',
    messagingSenderId: '901564160466',
    projectId: 'olympe-4f6cc',
    storageBucket: 'olympe-4f6cc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKUTvhlumPFDcZJzK8o17tlY6MznulQws',
    appId: '1:901564160466:ios:483706526e64a37ecfd00b',
    messagingSenderId: '901564160466',
    projectId: 'olympe-4f6cc',
    storageBucket: 'olympe-4f6cc.appspot.com',
    iosClientId: '901564160466-in9g1ajmc4o88efcp230omckh7dorpe1.apps.googleusercontent.com',
    iosBundleId: 'com.example.olympe',
  );
}
